version: '3.3'
services:
  sqlite-web:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - '/data:/data'
    environment:
      - SQLITE_DATABASE=db_filename.db
    image: coleifer/sqlite-web
